CREATE DATABASE cs4347project;

USE cs4347project;
#DROP TABLE PROFILE, GENERAL_PROFILE, ADMIN_PROFILE, ADVERTISER_PROFILE, TRANSACTIONS;
#DROP TABLE ADVERTISER_LISTINGS;

CREATE TABLE PROFILE(
	NetID VARCHAR(100) NOT NULL,
    Verification_Status BOOLEAN,
    Email VARCHAR(1000) NOT NULL,
    Buy_Rating INT,
    Sell_Rating INT,
    PRIMARY KEY(NetID)
);

CREATE TABLE GENERAL_PROFILE(
	NetID VARCHAR(100) NOT NULL,
	ProfileID INT NOT NULL,
	Transaction_History VARCHAR(45) NULL,
	PRIMARY KEY (`NetID`, `ProfileID`),
	CONSTRAINT `NetID`
    FOREIGN KEY (NetID) REFERENCES PROFILE(NetID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE ADMIN_PROFILE(
	NetID VARCHAR(100) NOT NULL,
	AdminID INT NOT NULL,
	PRIMARY KEY (`NetID`, `AdminID`),
	CONSTRAINT `NetID`
    FOREIGN KEY (NetID) REFERENCES PROFILE(NetID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE ADVERTISER_PROFILE(
	NetID VARCHAR(100) NOT NULL,
	AdvertiserID INT NOT NULL,
	PRIMARY KEY (`NetID`, `AdvertiserID`),
	CONSTRAINT `NetID`
    FOREIGN KEY (NetID) REFERENCES PROFILE(NetID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE TRANSACTIONS(
	TItemID INT NOT NULL,
    NetID VARCHAR(100) NOT NULL,
	SellerID INT NOT NULL,
    Price INT NOT NULL,
    CustomerID INT NOT NULL,
	PRIMARY KEY (`NetID`, `TItemID`),
	CONSTRAINT `NetID`
    FOREIGN KEY (NetID) REFERENCES PROFILE(NetID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
);

CREATE TABLE LISTINGS(
	ListingID INT NOT NULL,
    TItemID INT NOT NULL,
    NetID VARCHAR(100) NOT NULL,
    Date_Created DATE NOT NULL,
    DATE_Fulfilled DATE,
	Information VARCHAR(10000),
    PRIMARY KEY (`NetID`, `TItemID`, `ListingID`),
    CONSTRAINT `NetID`
    FOREIGN KEY (NetID) REFERENCES PROFILE(NetID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT `TItemID`
    FOREIGN KEY (TItemID) REFERENCES TRANSACTIONS(TItemID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE USER_LISTINGS(
	ListingID INT,
    NetID VARCHAR(100),
    Price INT,
    PRIMARY KEY (`NetID`, `ListingID`),
    CONSTRAINT `ListingID`
    FOREIGN KEY (ListingID) REFERENCES LISTINGS(ListingID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT `NetID`
    FOREIGN KEY (NetID) REFERENCES PROFILE(NetID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ADVERTISER_LISTINGS(
	ListingID INT,
    AdvertiserID VARCHAR(100),
    Price INT,
    PRIMARY KEY (`AdvertiserID`, `ListingID`),
    CONSTRAINT `ListingID`
    FOREIGN KEY (ListingID) REFERENCES LISTINGS(ListingID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT `AdvertiserID`
    FOREIGN KEY (AdvertiserID) REFERENCES ADVERTISER_PROFILE(AdvertiserID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE FORUM_POST(
	PostID INT,
    CItemID INT,
	NetID VARCHAR(100),
    PRIMARY KEY (`PostID`, `CItemID`, `NetID`),
	CONSTRAINT `NetID`
    FOREIGN KEY (NetID) REFERENCES PROFILE(NetID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT `CItemID`
    FOREIGN KEY (CItemID) REFERENCES CATEGORIES(CItemID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE USER_POST(
	PostID INT,
    UNetID VARCHAR(100),
    PRIMARY KEY (`PostID`, `UNetID`),
    CONSTRAINT `UNetID`
    FOREIGN KEY (UNetID) REFERENCES PROFILE(NetID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT `PostID`
    FOREIGN KEY (PostID) REFERENCES FORUNM_POST(PostID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ADVERTISER_POST(
	PostID INT,
    AdvertiserID VARCHAR(100),
    PRIMARY KEY (`PostID`, `AdvertiserID`),
    CONSTRAINT `AdvertiserID`
    FOREIGN KEY (AdvertiserID) REFERENCES ADVERISER_PROFILE(AdvertiserID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT `PostID`
    FOREIGN KEY (PostID) REFERENCES FORUNM_POST(PostID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);


